# build settings
title: [Mark's CIT 82 Public Site]
description: [This is my public site for CIT 82. A place to share my work and thoughts about web development and technology.]
show_downloads: [true]

# configuration file for Jekyll theme

# themes

# Cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Tactile
# remote_theme: pages-themes/tactile@v0.2.0
# include:
# - styles.css
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one


# Midnight
# remote_theme: pages-themes/midnight@v0.2.0
# include:
# - styles.css
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one


# Slate
# remote_theme: pages-themes/slate@v0.2.0
# include:
# - styles.css
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
