# configuration file for Jekyll theme

# build settings
title: Mark's CIT 82 Public Site
description: My public site for CIT 82 Introduction to Web Development Spring 2025
show_downloads: true

# themes

# Cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


# Tactile
# remote_theme: pages-themes/tactile@v0.2.0
# include:
# - styles.css
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one


# Midnight
# remote_theme: pages-themes/midnight@v0.2.0
# include:
# - styles.css
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one


# Slate
# remote_theme: pages-themes/slate@v0.2.0
# include:
# - styles.css
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
